### ISSUE TITLE
Reporte contrato

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-balam#1]
[CONTRATO DE DESARROLLO DE SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-balam/files/10179904/CONTRATO.DE.DESARROLLO.DE.SOFTWARE.pdf)

**Comment by salathiel1999** [comment]
50 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
